### ISSUE TITLE
Question: Static Site

### ISSUE THREAD

**Issue by candideu** [authorizerdev/authorizer-js#10]
Hi!

Is it possible to implement Authorizer in a Static Site, or Static Site builder like Publii CMS?

**Comment by lakhansamani** [comment]
Hi @candideu

Yes, it is possible to use Authorizer with static site.
You can checkout steps mentioned here: https://docs.authorizer.dev/authorizer-js

**Comment by candideu** [comment]
Sweet, thank you!
