### ISSUE TITLE
Token-based login and logout capabilities for multiple logins, account switching

### ISSUE THREAD

**Issue by blackMoja** [authorizerdev/authorizer-js#11]
**Feature Description**

Multiple token-based login capabilities are required in one application.

**Describe the solution you'd like**

Token or session-based login and logout functions are required for multiple users.

**Describe alternatives you've considered**

Currently, there is no token or session-based login/logout function, so there is no alternative.

**Additional context**

There is a request from the discode. The author is 98.mookey.
[Discord Link](https://discord.com/channels/880681510661926982/957534817719816192/1006512507994775583)

**Comment by lakhansamani** [comment]
Released as part of 1.3.5
