### ISSUE TITLE
Moving from rollup -> tsup increases bundle size

### ISSUE THREAD

**Issue by lakhansamani** [authorizerdev/authorizer-js#22]
**Version:** 1.2.0-beta.1

**Describe the bug**
Reverting the change for now as moving from rollup -> tsup increases bundle size a lot. Check the screenshot for reference

<img width="1674" alt="Screenshot 2023-03-24 at 1 37 13 PM" src="https://user-images.githubusercontent.com/6964334/227461830-5980b4c8-06b8-4740-ae30-b08554f40195.png">

<img width="1680" alt="Screenshot 2023-03-24 at 1 37 06 PM" src="https://user-images.githubusercontent.com/6964334/227461851-9730de77-cb44-462e-90f9-0346e74fc21c.png">

**Steps To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by lakhansamani** [comment]
@productdevbook pls check the side effect of this PR
https://github.com/authorizerdev/authorizer-js/pull/21

**Comment by productdevbook** [comment]
![image](https://user-images.githubusercontent.com/38668796/227463109-bfc6e49a-77b6-40d9-a8ed-03d7e9936246.png)


dont see tsup 1.2.1 ?

**Comment by productdevbook** [comment]
![image](https://user-images.githubusercontent.com/38668796/227464348-f8284a0e-c781-4fdd-b400-c29fe4010fe1.png)


this tsup dont problem

**Comment by lakhansamani** [comment]
@productdevbook check the index.global.js that is build

**Comment by productdevbook** [comment]
it seems to be correct because the output json there.
