### ISSUE TITLE
Error when calling getProfile

### ISSUE THREAD

**Issue by shiftlabs1** [authorizerdev/authorizer-js#27]
I get the error below when calling the function getProfile, with the right header info .I get the below 

<img width="1609" alt="Screenshot 2023-10-31 at 4 12 30 PM" src="https://github.com/authorizerdev/authorizer-js/assets/104312183/92664166-521a-4acf-9806-6c1d35cdf39e">

**Comment by shiftlabs1** [comment]
Am seeing thesame in the validateSessionCall. seems like a formatting issue ? 
<img width="1660" alt="Screenshot 2023-10-31 at 6 00 45 PM" src="https://github.com/authorizerdev/authorizer-js/assets/104312183/7f3ff9dd-9ee9-45fe-a798-8794a3eb14b7">

**Comment by lakhansamani** [comment]
@shiftlabs1 can you share authorizer version and authorizer-js version

**Comment by lakhansamani** [comment]
Thank you for sharing this I will fix it by EOD

**Comment by shiftlabs1** [comment]
Great! Thanks @lakhansamani

**Comment by lakhansamani** [comment]
There is error with validate session fixing that

**Comment by lakhansamani** [comment]
Fixed validating session in authorizer-js 1.2.11 & also fixed session validation for authorizer: in v1.2.1
