### ISSUE TITLE
Hasura Custom Claims Issue

### ISSUE THREAD

**Issue by shiftlabs1** [authorizerdev/authorizer-js#33]
I am using Authorizer with Hasura. I find that when i extend the default custom claims generating function from 
```
function(user,tokenPayload) {
  
var data = tokenPayload;
  data['https://hasura.io/jwt/claims'] = {
    'x-hasura-user-id': user.id,
    'x-hasura-default-role': tokenPayload.allowed_roles[0],
    'x-hasura-allowed-roles': user.roles
  }
 
  return data;
}
```
to 
```
function(user,tokenPayload) {
  
var data = tokenPayload;
  data['https://hasura.io/jwt/claims'] = {
    'x-hasura-user-id': user.id,
    'x-hasura-default-role': tokenPayload.allowed_roles[0],
    'x-hasura-allowed-roles': user.roles,
    'x-hasura-org-id': user.app_data?.orgId
  }
 
  return data;
}
```
 To include other data that i need to use with hasura from the app_data property of user , "'https://hasura.io/jwt/claims'' of the claims is omitted but i get no error . Does Authorizer fix this function string and discard anything else. Cos i see no reason why this would not generate Hasura claims when i include more properties (which is allowed)

**Comment by shiftlabs1** [comment]
Ok, i got past this issue by using 
```tokenPayload.app_data.orgId```
And got the hasura claims generated correctly. I don't know what format the user object is here but i couldn't get app_data?.orgId out of it . I saw from the code in auth_token.go that tokenPayload already contains all the data from user . so that worked for me

**Comment by lakhansamani** [comment]
@shiftlabs1 thank you for sharing this,
I think `app_data` should be part of user only,
Will check and get back

Thanks

**Comment by shiftlabs1** [comment]
The issue is , it does not seem to be a part of user. I am fine with it being a part of tokenPayload. removing it from tokenPayload and not including as part of user will keep this an existing issue . It should be a part of both actually

**Comment by lakhansamani** [comment]
Yes 👍

**Comment by lakhansamani** [comment]
@shiftlabs1 its kind of working for me
https://www.loom.com/share/1ed432fb6daf4ee991bec19fda9ee07f?from_recorder=1&focus_title=1
