### ISSUE TITLE
The getToken call fails without a proper error message.

### ISSUE THREAD

**Issue by agarwal-nitesh** [authorizerdev/authorizer-js#5]
Client: Mobile
The login call with `"scope":["openid","email","profile","offline_access"]` is successful. The `getToken` call with `grant_type` `refresh_token` and the refresh token obtained from the login call, fails. The failure message string contains object ( `"[Error: [object Object]]"`) instead of the actual error message or object.

**Comment by lakhansamani** [comment]
Resolved here: https://github.com/authorizerdev/authorizer-js/commit/0376a987628b8e2c90607df58d3c4b59fa0f92b5
